// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { resolveDatabaseUrl } from "./src/lib/db-url";

const url = resolveDatabaseUrl();

if (!url) {
  throw new Error(
    "Database connection string not found. Set the DATABASE_URL environment variable (or POSTGRES_URL) to your PostgreSQL connection string.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url,
  },
});
